const SUPABASE_URL="https://lcqbdjfobexvpjjadide.supabase.co";
const SUPABASE_PUBLISHABLE_KEY="sb_publishable_4jhHRRJkk7QVyov8aJbK7w_sRbgsCOk";
let supabase=null,cloudMode=false;
const state={staff:[],services:[],invoices:[],invoiceItems:[],draft:[],access:null};
const LS={staff:"salonsync_staff_v1",services:"salonsync_services_v1",invoices:"salonsync_invoices_v1",items:"salonsync_invoice_items_v1"};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat("vi-VN").format(Number(n||0))+" ₫";
const esc=(v="")=>String(v).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const uid=()=>crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;
const dateKey=d=>{const x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,"0")}-${String(x.getDate()).padStart(2,"0")}`};
const monthKey=d=>dateKey(d).slice(0,7);
function toast(msg){const el=$("#toast");el.textContent=msg;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2200)}
function isCloudConfigured(){return SUPABASE_URL.startsWith("https://")&&!SUPABASE_URL.includes("YOUR_")&&!SUPABASE_PUBLISHABLE_KEY.includes("YOUR_")}
const accessLabel=r=>({owner:"Chủ salon",manager:"Quản lý",reception:"Lễ tân",stylist:"Thợ tóc"})[r]||r||"";
const can=(...roles)=>!cloudMode||roles.includes(state.access?.access_role);
function allowedViews(){if(!cloudMode)return["dashboard","pos","invoices","commission","services","staff"];const r=state.access?.access_role;if(r==="owner"||r==="manager")return["dashboard","pos","invoices","commission","services","staff"];if(r==="reception")return["dashboard","pos","invoices","services","staff"];if(r==="stylist")return["commission","services"];return[]}
function applyRoleUI(){
  const allowed=new Set(allowedViews());
  $(".nav-item").forEach(x=>x.classList.toggle("hidden",!allowed.has(x.dataset.view)));
  $("#goPosBtn").classList.toggle("hidden",cloudMode&&!allowed.has("pos"));
  const edit=can("owner","manager");
  const sf=$("#servicesView .form-panel"),tf=$("#staffView .form-panel");
  if(sf)sf.classList.toggle("hidden",cloudMode&&!edit);
  if(tf)tf.classList.toggle("hidden",cloudMode&&!edit);
  const commissionMetric=$("#monthCommission")?.closest(".metric-card");
  const commissionPanel=$("#topCommission")?.closest(".panel");
  const canSeeAllCommission=can("owner","manager");
  if(commissionMetric)commissionMetric.classList.toggle("hidden",cloudMode&&!canSeeAllCommission);
  if(commissionPanel)commissionPanel.classList.toggle("hidden",cloudMode&&!canSeeAllCommission);
}
function setCloudStatus(on,email="",role=""){cloudMode=on;$("#syncDot").classList.toggle("online",on);$("#syncLabel").textContent=on?"Đang đồng bộ cloud":"Demo trên máy này";$("#currentUser").textContent=on?`${email||"Đã đăng nhập"}${role?" • "+accessLabel(role):""}`:"Demo";$("#logoutBtn").classList.toggle("hidden",!on);applyRoleUI()}
function seedLocal(){if(!localStorage.getItem(LS.staff))localStorage.setItem(LS.staff,JSON.stringify([{id:uid(),name:"Hoàng",role:"stylist",active:true},{id:uid(),name:"Linh",role:"stylist",active:true},{id:uid(),name:"Nam",role:"stylist",active:true}]));if(!localStorage.getItem(LS.services))localStorage.setItem(LS.services,JSON.stringify([{id:uid(),name:"Cắt tóc nam",price:150000,commission_rate:30,active:true},{id:uid(),name:"Cắt + gội",price:180000,commission_rate:30,active:true},{id:uid(),name:"Uốn tóc",price:450000,commission_rate:25,active:true},{id:uid(),name:"Nhuộm tóc",price:650000,commission_rate:20,active:true},{id:uid(),name:"Phục hồi tóc",price:300000,commission_rate:25,active:true},{id:uid(),name:"Combo tạo kiểu",price:250000,commission_rate:30,active:true}]));if(!localStorage.getItem(LS.invoices)){localStorage.setItem(LS.invoices,"[]");localStorage.setItem(LS.items,"[]")}}
function loadLocal(){seedLocal();state.staff=JSON.parse(localStorage.getItem(LS.staff)||"[]");state.services=JSON.parse(localStorage.getItem(LS.services)||"[]");state.invoices=JSON.parse(localStorage.getItem(LS.invoices)||"[]");state.invoiceItems=JSON.parse(localStorage.getItem(LS.items)||"[]");renderAll()}
function saveLocal(){localStorage.setItem(LS.staff,JSON.stringify(state.staff));localStorage.setItem(LS.services,JSON.stringify(state.services));localStorage.setItem(LS.invoices,JSON.stringify(state.invoices));localStorage.setItem(LS.items,JSON.stringify(state.invoiceItems))}
async function initSupabase(){if(!isCloudConfigured()){ $("#loginOverlay").classList.remove("hidden");return }try{const mod=await import("https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm");supabase=mod.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);const {data:{session}}=await supabase.auth.getSession();if(session){$("#loginOverlay").classList.add("hidden");setCloudStatus(true,session.user.email);await loadCloud();subscribeRealtime()}else $("#loginOverlay").classList.remove("hidden")}catch(e){console.error(e);$("#loginOverlay").classList.remove("hidden");toast("Không kết nối được Supabase")}}
async function loadCloud(){
  const acct=await supabase.from("user_accounts").select("user_id,staff_id,access_role,active").single();
  if(acct.error||!acct.data?.active){
    state.access=null;
    toast("Tài khoản chưa được cấp quyền sử dụng SalonSync");
    await supabase.auth.signOut();
    $("#loginOverlay").classList.remove("hidden");
    return false;
  }
  state.access=acct.data;
  const [a,b,c,d]=await Promise.all([
    supabase.from("staff").select("*").order("name"),
    supabase.from("services").select("*").order("name"),
    supabase.from("invoices").select("*").order("created_at",{ascending:false}),
    supabase.from("invoice_items").select("*")
  ]);
  const err=[a.error,b.error,c.error,d.error].find(Boolean);
  if(err){toast(err.message);return false}
  state.staff=a.data||[];state.services=b.data||[];state.invoices=c.data||[];state.invoiceItems=d.data||[];
  const {data:{user}}=await supabase.auth.getUser();
  setCloudStatus(true,user?.email||"",state.access.access_role);
  renderAll();
  const first=allowedViews()[0];
  if(first&&!allowedViews().includes($(".nav-item.active")[0]?.dataset.view))showView(first);
  return true
}
function subscribeRealtime(){supabase.channel("salonsync").on("postgres_changes",{event:"*",schema:"public",table:"staff"},loadCloud).on("postgres_changes",{event:"*",schema:"public",table:"services"},loadCloud).on("postgres_changes",{event:"*",schema:"public",table:"invoices"},loadCloud).on("postgres_changes",{event:"*",schema:"public",table:"invoice_items"},loadCloud).subscribe()}
async function createService(){if(cloudMode&&!can("owner","manager"))return toast("Bạn không có quyền sửa dịch vụ");const name=$("#newServiceName").value.trim(),price=Number($("#newServicePrice").value||0),commission_rate=Number($("#newServiceCommission").value||0);if(!name)return toast("Nhập tên dịch vụ");if(cloudMode){const {error}=await supabase.from("services").insert({name,price,commission_rate,active:true});if(error)return toast(error.message)}else{state.services.push({id:uid(),name,price,commission_rate,active:true});saveLocal();renderAll()}$("#newServiceName").value="";toast("Đã thêm dịch vụ")}
async function createStaff(){if(cloudMode&&!can("owner","manager"))return toast("Bạn không có quyền quản lý nhân viên");const name=$("#newStaffName").value.trim(),role=$("#newStaffRole").value;if(!name)return toast("Nhập tên nhân viên");if(cloudMode){const {error}=await supabase.from("staff").insert({name,role,active:true});if(error)return toast(error.message)}else{state.staff.push({id:uid(),name,role,active:true});saveLocal();renderAll()}$("#newStaffName").value="";toast("Đã thêm nhân viên")}
async function removeService(id){if(cloudMode&&!can("owner","manager"))return toast("Bạn không có quyền sửa dịch vụ");if(!confirm("Ẩn dịch vụ này?"))return;if(cloudMode){const {error}=await supabase.from("services").update({active:false}).eq("id",id);if(error)return toast(error.message)}else{state.services=state.services.map(x=>x.id===id?{...x,active:false}:x);saveLocal();renderAll()}}
async function removeStaff(id){if(cloudMode&&!can("owner","manager"))return toast("Bạn không có quyền quản lý nhân viên");if(!confirm("Ẩn nhân viên này?"))return;if(cloudMode){const {error}=await supabase.from("staff").update({active:false}).eq("id",id);if(error)return toast(error.message)}else{state.staff=state.staff.map(x=>x.id===id?{...x,active:false}:x);saveLocal();renderAll()}}
function addToDraft(id){const s=state.services.find(x=>x.id===id);if(!s)return;state.draft.push({line_id:uid(),service_id:s.id,service_name:s.name,qty:1,unit_price:Number(s.price||0),staff_id:"",staff_name:"",commission_rate:Number(s.commission_rate||0)});renderDraft()}
function updateDraftLine(id,field,value){const l=state.draft.find(x=>x.line_id===id);if(!l)return;if(["qty","unit_price","commission_rate"].includes(field))value=Number(value||0);l[field]=value;if(field==="staff_id"){const st=state.staff.find(x=>x.id===value);l.staff_name=st?.name||""}renderDraft()}
function removeDraftLine(id){state.draft=state.draft.filter(x=>x.line_id!==id);renderDraft()}
function draftTotals(){const subtotal=state.draft.reduce((s,l)=>s+l.qty*l.unit_price,0),commission=state.draft.reduce((s,l)=>s+l.qty*l.unit_price*l.commission_rate/100,0),discount=Math.max(0,Number($("#discountInput").value||0));return{subtotal,discount,total:Math.max(0,subtotal-discount),commission}}
function renderDraft(){const w=$("#billItems");w.innerHTML=state.draft.length?state.draft.map(l=>`<div class="bill-item"><div class="bill-item-top"><div class="bill-item-name">${esc(l.service_name)}</div><div class="bill-item-price">${money(l.qty*l.unit_price)}</div></div><div class="bill-item-controls"><select class="input draft-control" data-id="${l.line_id}" data-field="staff_id"><option value="">Chọn nhân viên</option>${state.staff.filter(x=>x.active).map(st=>`<option value="${st.id}" ${st.id===l.staff_id?"selected":""}>${esc(st.name)}</option>`).join("")}</select><input class="input draft-control" data-id="${l.line_id}" data-field="unit_price" type="number" min="0" value="${l.unit_price}"><input class="input draft-control" data-id="${l.line_id}" data-field="commission_rate" type="number" min="0" max="100" value="${l.commission_rate}"><button class="icon-btn" data-remove-line="${l.line_id}">×</button></div></div>`).join(""):'<div class="empty">Chưa có dịch vụ trong hóa đơn.</div>';const t=draftTotals();$("#subTotal").textContent=money(t.subtotal);$("#grandTotal").textContent=money(t.total);$("#billCommission").textContent=money(t.commission)}
function nextInvoiceNo(){const m=state.invoices.reduce((v,x)=>Math.max(v,Number(String(x.invoice_no||"").replace(/\D/g,""))||0),0);return"HD"+String(m+1).padStart(4,"0")}
async function payInvoice(){if(cloudMode&&!can("owner","manager","reception"))return toast("Bạn không có quyền tạo hóa đơn");if(!state.draft.length)return toast("Hóa đơn chưa có dịch vụ");if(state.draft.some(x=>!x.staff_id))return toast("Chọn nhân viên cho tất cả dịch vụ");const customer_name=$("#customerName").value.trim()||"Khách lẻ",customer_phone=$("#customerPhone").value.trim(),payment_method=$("#paymentMethod").value,t=draftTotals(),invoice_no=nextInvoiceNo();let invoice=null;if(cloudMode){const res=await supabase.from("invoices").insert({customer_name,customer_phone,subtotal:t.subtotal,discount:t.discount,total:t.total,commission_total:t.commission,payment_method,status:"paid"}).select().single();invoice=res.data;if(res.error)return toast(res.error.message);const items=state.draft.map(l=>({invoice_id:invoice.id,service_id:l.service_id,service_name:l.service_name,staff_id:l.staff_id,staff_name:l.staff_name,qty:l.qty,unit_price:l.unit_price,commission_rate:l.commission_rate,line_total:l.qty*l.unit_price,commission_amount:l.qty*l.unit_price*l.commission_rate/100}));const {error}=await supabase.from("invoice_items").insert(items);if(error)return toast(error.message)}else{const id=uid();state.invoices.unshift({id,invoice_no,customer_name,customer_phone,subtotal:t.subtotal,discount:t.discount,total:t.total,commission_total:t.commission,payment_method,status:"paid",created_at:new Date().toISOString()});state.invoiceItems.push(...state.draft.map(l=>({id:uid(),invoice_id:id,service_id:l.service_id,service_name:l.service_name,staff_id:l.staff_id,staff_name:l.staff_name,qty:l.qty,unit_price:l.unit_price,commission_rate:l.commission_rate,line_total:l.qty*l.unit_price,commission_amount:l.qty*l.unit_price*l.commission_rate/100})));saveLocal();renderAll()}const saved=cloudMode?invoice.invoice_no:invoice_no;state.draft=[];$("#customerName").value="";$("#customerPhone").value="";$("#discountInput").value=0;renderDraft();toast("Đã lưu "+saved);showView("dashboard")}
function renderDashboard(){const now=new Date(),tk=dateKey(now),mk=monthKey(now),paid=state.invoices.filter(x=>x.status==="paid"),today=paid.filter(x=>dateKey(x.created_at)===tk),month=paid.filter(x=>monthKey(x.created_at)===mk);$("#todayRevenue").textContent=money(today.reduce((s,x)=>s+Number(x.total||0),0));$("#todayInvoices").textContent=`${today.length} hóa đơn`;$("#monthRevenue").textContent=money(month.reduce((s,x)=>s+Number(x.total||0),0));$("#monthInvoices").textContent=`${month.length} hóa đơn`;$("#monthCommission").textContent=money(month.reduce((s,x)=>s+Number(x.commission_total||0),0));$("#monthCustomers").textContent=new Set(month.map(x=>x.customer_phone).filter(Boolean)).size;const recent=[...paid].sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)).slice(0,6);$("#recentInvoices").innerHTML=recent.length?`<div class="table-wrap"><table><thead><tr><th>Mã</th><th>Khách</th><th>Tổng</th><th>Thời gian</th></tr></thead><tbody>${recent.map(x=>`<tr data-invoice-id="${x.id}"><td class="td-main">${esc(x.invoice_no)}</td><td><div class="td-main">${esc(x.customer_name)}</div><div class="td-sub">${esc(x.customer_phone||"")}</div></td><td>${money(x.total)}</td><td>${new Date(x.created_at).toLocaleString("vi-VN")}</td></tr>`).join("")}</tbody></table></div>`:'<div class="empty">Chưa có hóa đơn.</div>';const ids=new Set(month.map(x=>x.id)),comm={};state.invoiceItems.filter(i=>ids.has(i.invoice_id)).forEach(i=>comm[i.staff_name]=(comm[i.staff_name]||0)+Number(i.commission_amount||0));const ranked=Object.entries(comm).sort((a,b)=>b[1]-a[1]).slice(0,7);$("#topCommission").innerHTML=ranked.length?`<div class="rank-list">${ranked.map(([n,v],i)=>`<div class="rank-row"><div class="rank-num">${i+1}</div><div class="rank-name">${esc(n)}</div><div class="rank-value">${money(v)}</div></div>`).join("")}</div>`:'<div class="empty">Chưa có dữ liệu hoa hồng.</div>'}
function renderServiceCatalog(){const q=($("#serviceSearch")?.value||"").trim().toLowerCase(),list=state.services.filter(x=>x.active&&x.name.toLowerCase().includes(q));$("#serviceCatalog").innerHTML=list.length?list.map(s=>`<button class="service-card" data-add-service="${s.id}"><div class="name">${esc(s.name)}</div><div class="meta">${money(s.price)} · HH ${Number(s.commission_rate||0)}%</div></button>`).join(""):'<div class="empty">Không tìm thấy dịch vụ.</div>'}
function paymentLabel(v){return({cash:"Tiền mặt",bank:"Chuyển khoản",card:"Thẻ"})[v]||v||"-"}
function renderInvoices(){const q=($("#invoiceSearch")?.value||"").trim().toLowerCase(),list=state.invoices.filter(x=>!q||`${x.invoice_no} ${x.customer_name} ${x.customer_phone}`.toLowerCase().includes(q)).sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));$("#invoiceTable").innerHTML=list.length?`<div class="table-wrap"><table><thead><tr><th>Mã HĐ</th><th>Khách</th><th>Tổng tiền</th><th>Hoa hồng</th><th>Thanh toán</th><th>Thời gian</th></tr></thead><tbody>${list.map(x=>`<tr data-invoice-id="${x.id}"><td class="td-main">${esc(x.invoice_no)}</td><td><div class="td-main">${esc(x.customer_name)}</div><div class="td-sub">${esc(x.customer_phone||"")}</div></td><td>${money(x.total)}</td><td>${money(x.commission_total)}</td><td>${paymentLabel(x.payment_method)}</td><td>${new Date(x.created_at).toLocaleString("vi-VN")}</td></tr>`).join("")}</tbody></table></div>`:'<div class="empty">Chưa có hóa đơn phù hợp.</div>'}
function renderCommission(){const selected=$("#commissionMonth").value||monthKey(new Date()),ids=new Set(state.invoices.filter(x=>x.status==="paid"&&monthKey(x.created_at)===selected).map(x=>x.id)),by={};state.invoiceItems.filter(i=>ids.has(i.invoice_id)).forEach(i=>{const k=i.staff_id||i.staff_name;if(!by[k])by[k]={name:i.staff_name||"Không rõ",revenue:0,commission:0,services:0};by[k].revenue+=Number(i.line_total||0);by[k].commission+=Number(i.commission_amount||0);by[k].services+=Number(i.qty||1)});const rows=Object.values(by).sort((a,b)=>b.commission-a.commission);$("#commissionTable").innerHTML=rows.length?`<div class="table-wrap"><table><thead><tr><th>Nhân viên</th><th>Số dịch vụ</th><th>Doanh số thực hiện</th><th>Hoa hồng</th></tr></thead><tbody>${rows.map(r=>`<tr><td class="td-main">${esc(r.name)}</td><td>${r.services}</td><td>${money(r.revenue)}</td><td class="td-main">${money(r.commission)}</td></tr>`).join("")}</tbody></table></div>`:'<div class="empty">Tháng này chưa có dữ liệu.</div>'}
function roleLabel(r){return({stylist:"Thợ tóc",reception:"Lễ tân",manager:"Quản lý"})[r]||r}
function renderAdmin(){const edit=can("owner","manager");$("#serviceAdminList").innerHTML=state.services.filter(x=>x.active).map(s=>`<div class="admin-row"><div><strong>${esc(s.name)}</strong><small>${money(s.price)} · Hoa hồng ${Number(s.commission_rate||0)}%</small></div>${edit?`<button class="danger-btn" data-remove-service="${s.id}">Ẩn</button>`:""}</div>`).join("")||'<div class="empty">Chưa có dịch vụ.</div>';$("#staffAdminList").innerHTML=state.staff.filter(x=>x.active).map(s=>`<div class="admin-row"><div><strong>${esc(s.name)}</strong><small>${roleLabel(s.role)}</small></div>${edit?`<button class="danger-btn" data-remove-staff="${s.id}">Ẩn</button>`:""}</div>`).join("")||'<div class="empty">Chưa có nhân viên.</div>';applyRoleUI()}
function openInvoice(id){const inv=state.invoices.find(x=>x.id===id);if(!inv)return;const items=state.invoiceItems.filter(x=>x.invoice_id===id);$("#invoiceDetail").innerHTML=`<div class="detail"><div class="detail-grid"><div class="detail-box"><span>Mã hóa đơn</span><strong>${esc(inv.invoice_no)}</strong></div><div class="detail-box"><span>Thời gian</span><strong>${new Date(inv.created_at).toLocaleString("vi-VN")}</strong></div><div class="detail-box"><span>Khách hàng</span><strong>${esc(inv.customer_name)}</strong></div><div class="detail-box"><span>Số điện thoại</span><strong>${esc(inv.customer_phone||"-")}</strong></div></div><div class="table-wrap"><table><thead><tr><th>Dịch vụ</th><th>Nhân viên</th><th>Giá</th><th>% HH</th><th>Hoa hồng</th></tr></thead><tbody>${items.map(i=>`<tr><td>${esc(i.service_name)}</td><td>${esc(i.staff_name)}</td><td>${money(i.line_total)}</td><td>${Number(i.commission_rate)}%</td><td>${money(i.commission_amount)}</td></tr>`).join("")}</tbody></table></div></div>`;$("#invoiceModal").classList.remove("hidden")}
function exportCsv(){const h=["Ma HD","Khach hang","SDT","Tam tinh","Giam gia","Tong tien","Hoa hong","Thanh toan","Thoi gian"],rows=state.invoices.map(x=>[x.invoice_no,x.customer_name,x.customer_phone,x.subtotal,x.discount,x.total,x.commission_total,paymentLabel(x.payment_method),new Date(x.created_at).toLocaleString("vi-VN")]);const csv=[h,...rows].map(r=>r.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n"),blob=new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`salon-invoices-${dateKey(new Date())}.csv`;a.click();URL.revokeObjectURL(a.href)}
function renderAll(){renderDashboard();renderServiceCatalog();renderDraft();renderInvoices();renderCommission();renderAdmin()}
const meta={dashboard:["Tổng quan","Theo dõi doanh thu và hoa hồng salon"],pos:["Tạo hóa đơn","Chọn dịch vụ, nhân viên và thanh toán"],invoices:["Hóa đơn","Tra cứu hóa đơn đã thanh toán"],commission:["Hoa hồng","Tổng hợp hoa hồng theo nhân viên"],services:["Dịch vụ","Quản lý giá và tỷ lệ hoa hồng"],staff:["Nhân viên","Quản lý đội ngũ salon"]};
function showView(n){if(cloudMode&&!allowedViews().includes(n))return toast("Bạn không có quyền truy cập mục này");$(".view").forEach(x=>x.classList.remove("active"));$$(".nav-item").forEach(x=>x.classList.toggle("active",x.dataset.view===n));$("#"+n+"View").classList.add("active");$("#pageTitle").textContent=meta[n][0];$("#pageSubtitle").textContent=meta[n][1];if(n==="commission")renderCommission();if(n==="invoices")renderInvoices()}
document.addEventListener("click",async e=>{const nav=e.target.closest("[data-view]");if(nav)showView(nav.dataset.view);const jump=e.target.closest("[data-jump]");if(jump)showView(jump.dataset.jump);const add=e.target.closest("[data-add-service]");if(add)addToDraft(add.dataset.addService);const rem=e.target.closest("[data-remove-line]");if(rem)removeDraftLine(rem.dataset.removeLine);const inv=e.target.closest("[data-invoice-id]");if(inv)openInvoice(inv.dataset.invoiceId);const rs=e.target.closest("[data-remove-service]");if(rs)await removeService(rs.dataset.removeService);const rt=e.target.closest("[data-remove-staff]");if(rt)await removeStaff(rt.dataset.removeStaff)});
document.addEventListener("change",e=>{const c=e.target.closest(".draft-control");if(c)updateDraftLine(c.dataset.id,c.dataset.field,c.value)});
$("#serviceSearch").addEventListener("input",renderServiceCatalog);$("#invoiceSearch").addEventListener("input",renderInvoices);$("#discountInput").addEventListener("input",renderDraft);$("#commissionMonth").value=monthKey(new Date());$("#commissionMonth").addEventListener("change",renderCommission);$("#addServiceBtn").addEventListener("click",createService);$("#addStaffBtn").addEventListener("click",createStaff);$("#payBtn").addEventListener("click",payInvoice);$("#clearBillBtn").addEventListener("click",()=>{state.draft=[];renderDraft()});$("#goPosBtn").addEventListener("click",()=>showView("pos"));$("#exportCsvBtn").addEventListener("click",exportCsv);$("#closeInvoiceModal").addEventListener("click",()=>$("#invoiceModal").classList.add("hidden"));$("#invoiceModal").addEventListener("click",e=>{if(e.target.id==="invoiceModal")$("#invoiceModal").classList.add("hidden")});$("#demoBtn").addEventListener("click",()=>{$("#loginOverlay").classList.add("hidden");setCloudStatus(false);loadLocal()});$("#loginBtn").addEventListener("click",async()=>{const email=$("#loginEmail").value.trim(),password=$("#loginPassword").value;const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error)return toast(error.message);$("#loginOverlay").classList.add("hidden");setCloudStatus(true,data.user.email);await loadCloud();subscribeRealtime()});$("#logoutBtn").addEventListener("click",async()=>{if(supabase)await supabase.auth.signOut();$("#loginOverlay").classList.remove("hidden")});initSupabase();